# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: learnweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: my-app
          image: it21349560/order-serviceprod:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
      imagePullSecrets:
        - name: regcred
