# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: ctse
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3001
  selector:
    app: gateway-service
